apiVersion: v1
kind: Service
metadata:
  name: {{ include "topics.fullname" . }}
  labels:
    # {{- include "topics.labels" . | nindent 4 }}
    monitoring: enabled
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "80"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "topics.selectorLabels" . | nindent 4 }}
