apiVersion: v1
kind: Service
metadata:
  name: {{ include "traffic.fullname" . }}
  labels:
    {{- include "traffic.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "traffic.selectorLabels" . | nindent 4 }}
